export const styles = {
  page: {
    minHeight: "100vh",
    backgroundColor: "#f7f5f1",
    color: "#222",
  },
  container: {
    maxWidth: "1200px",
    margin: "0 auto",
    padding: "0 clamp(16px, 3vw, 28px)",
  },
  nav: {
    position: "sticky",
    top: 0,
    zIndex: 20,
    backgroundColor: "rgba(247,245,241,0.96)",
    borderBottom: "1px solid #ddd",
  },
  navInner: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "14px 0",
    flexWrap: "wrap",
    gap: "10px 16px",
  },
  navButton: {
    background: "none",
    border: "none",
    cursor: "pointer",
    fontSize: "clamp(14px, 1.8vw, 15px)",
    color: "#555",
    textDecoration: "underline",
    textUnderlineOffset: "4px",
    padding: "8px 0",
    textAlign: "center",
  },
  navButtonActive: {
    color: "#111",
    fontWeight: "bold",
  },
  heroTop: {
    textAlign: "center",
    paddingTop: "clamp(18px, 4vw, 32px)",
  },
  smallText: {
    fontSize: "clamp(13px, 1.8vw, 14px)",
    color: "#666",
  },
  title: {
    marginTop: "20px",
    fontSize: "clamp(32px, 6vw, 56px)",
    fontWeight: 300,
    lineHeight: 1.1,
  },
  primaryButton: {
    marginTop: "24px",
    backgroundColor: "#c8102e",
    color: "white",
    border: "none",
    borderRadius: "999px",
    padding: "clamp(12px, 2vw, 16px) clamp(20px, 4vw, 30px)",
    fontSize: "clamp(16px, 2.2vw, 18px)",
    cursor: "pointer",
    maxWidth: "100%",
  },
  section: {
    padding: "clamp(40px, 7vw, 72px) 0",
    textAlign: "center",
  },
  sectionTitle: {
    fontSize: "clamp(28px, 5vw, 42px)",
    fontWeight: 300,
    marginBottom: "16px",
    lineHeight: 1.15,
  },
  sectionDesc: {
    maxWidth: "800px",
    margin: "0 auto",
    fontSize: "clamp(17px, 2.6vw, 22px)",
    color: "#555",
    lineHeight: 1.5,
  },
  threeCol: {
    display: "grid",
    gridTemplateColumns: "repeat(3, 1fr)",
    gap: "28px",
    marginTop: "44px",
  },
  featureCard: {
    backgroundColor: "#fff",
    borderRadius: "20px",
    padding: "clamp(20px, 3vw, 28px)",
    border: "1px solid #e5e5e5",
  },
  featuredDealsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(2, 1fr)",
    gap: "24px",
    marginTop: "36px",
  },
  featuredCard: {
    backgroundColor: "#fff",
    border: "1px solid #e5e5e5",
    borderRadius: "24px",
    padding: "clamp(20px, 3vw, 28px)",
    textAlign: "left",
  },
  featuredEmoji: {
    fontSize: "clamp(42px, 7vw, 56px)",
    marginBottom: "16px",
  },
  searchWrap: {
    maxWidth: "800px",
    margin: "28px auto 0",
    display: "flex",
    alignItems: "center",
    gap: "10px",
    backgroundColor: "#e9e9e9",
    borderRadius: "999px",
    padding: "12px clamp(14px, 3vw, 18px)",
  },
  input: {
    flex: 1,
    border: "none",
    background: "transparent",
    outline: "none",
    fontSize: "clamp(15px, 2vw, 16px)",
  },
  filters: {
    marginTop: "28px",
    display: "flex",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: "10px",
  },
  filterButton: {
    borderRadius: "999px",
    padding: "10px 16px",
    border: "1px solid #ddd",
    backgroundColor: "#e9e9e9",
    cursor: "pointer",
    fontSize: "clamp(14px, 1.9vw, 15px)",
  },
  filterButtonActive: {
    backgroundColor: "#c8102e",
    color: "white",
    border: "1px solid #c8102e",
  },
  dealsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(3, 1fr)",
    gap: "clamp(16px, 2.6vw, 28px)",
    padding: "clamp(28px, 5vw, 50px) 0",
  },
  dealCard: {
    backgroundColor: "#fdeef1",
    padding: "clamp(22px, 3vw, 28px) clamp(16px, 2.5vw, 20px)",
    textAlign: "center",
    minHeight: "320px",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    borderRadius: "18px",
  },
  iconCircle: {
    width: "clamp(96px, 13vw, 140px)",
    height: "clamp(96px, 13vw, 140px)",
    borderRadius: "50%",
    backgroundColor: "#fff",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    margin: "0 auto clamp(18px, 3vw, 24px)",
    boxShadow: "0 4px 12px rgba(0, 0, 0, 0.08)",
  },
  dealBrand: {
    marginTop: "18px",
    fontSize: "clamp(24px, 3vw, 30px)",
    fontWeight: 600,
    lineHeight: 1.2,
  },
  dealTitle: {
    marginTop: "14px",
    fontSize: "clamp(17px, 2.7vw, 22px)",
    lineHeight: 1.4,
  },
  logoImage: {
    width: "clamp(52px, 7vw, 68px)",
    height: "clamp(52px, 7vw, 68px)",
    objectFit: "contain",
  },
  meta: {
    marginTop: "auto",
    paddingTop: "18px",
    fontSize: "clamp(13px, 1.8vw, 14px)",
    color: "#666",
  },
  pager: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    gap: "10px",
    paddingBottom: "32px",
    flexWrap: "wrap",
  },
  pagerButton: {
    border: "1px solid #ccc",
    backgroundColor: "white",
    borderRadius: "10px",
    padding: "8px 14px",
    cursor: "pointer",
    minWidth: "72px",
  },
  footer: {
    backgroundColor: "#555",
    color: "white",
    marginTop: "40px",
    paddingTop: "18px",
  },
  footerGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "24px",
    padding: "20px 0 clamp(32px, 5vw, 50px)",
  },
  footerTitle: {
    fontSize: "clamp(24px, 4vw, 30px)",
    fontWeight: 600,
    marginBottom: "12px",
  },
  footerText: {
    fontSize: "clamp(16px, 2.4vw, 20px)",
    lineHeight: 1.6,
    color: "rgba(255,255,255,0.9)",
  },
  footerIcons: {
    display: "flex",
    gap: "16px",
    alignItems: "center",
    justifyContent: "flex-start",
    marginBottom: "24px",
    marginLeft: "0",
  },
  copyright: {
    fontSize: "clamp(12px, 1.8vw, 14px)",
    color: "rgba(255,255,255,0.8)",
    paddingBottom: "18px",
  },
  fullImageCard: {
    marginTop: "clamp(24px, 4vw, 36px)",
    borderRadius: "28px",
    overflow: "hidden",
    boxShadow: "0 2px 8px rgba(0,0,0,0.05)",
  },
  fullImage: {
    width: "100%",
    display: "block",
    borderRadius: "28px",
  },
  middleImageCard: {
    marginTop: "10px",
    marginBottom: "clamp(20px, 4vw, 30px)",
    borderRadius: "28px",
    overflow: "hidden",
  },
  middleImage: {
    width: "100%",
    display: "block",
    borderRadius: "28px",
  },
  footerHeroCard: {
    position: "relative",
    marginTop: "clamp(30px, 6vw, 50px)",
    borderRadius: "28px",
    overflow: "hidden",
  },
  footerHeroImage: {
    width: "100%",
    display: "block",
    borderRadius: "28px",
  },
  footerHeroOverlay: {
    position: "absolute",
    left: "50%",
    bottom: "8%",
    transform: "translateX(-50%)",
    textAlign: "center",
    width: "min(80%, 760px)",
    zIndex: 2,
  },
  footerHeroTitle: {
    fontSize: "clamp(28px, 5.5vw, 48px)",
    fontWeight: 500,
    color: "white",
    marginBottom: "24px",
    textShadow: "0 2px 8px rgba(0,0,0,0.4)",
    lineHeight: 1.1,
  },
  footerHeroButton: {
    backgroundColor: "#c8102e",
    color: "white",
    border: "none",
    borderRadius: "999px",
    padding: "clamp(12px, 2vw, 16px) clamp(22px, 4vw, 36px)",
    fontSize: "clamp(16px, 3vw, 24px)",
    cursor: "pointer",
    boxShadow: "0 4px 12px rgba(0,0,0,0.25)",
    maxWidth: "100%",
  },
  footerHeroShade: {
    position: "absolute",
    inset: 0,
    backgroundColor: "rgba(0, 0, 0, 0.4)",
  },
  socialLink: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    textDecoration: "none",
  },
  socialIcon: {
    width: "clamp(22px, 3vw, 24px)",
    height: "clamp(22px, 3vw, 24px)",
    objectFit: "contain",
  },
  budgetSection: {
    maxWidth: "1200px",
    margin: "0 auto",
    padding: "clamp(40px, 6vw, 60px) clamp(16px, 3vw, 24px) clamp(34px, 5vw, 50px)",
    textAlign: "center",
  },
  budgetTitle: {
    fontSize: "clamp(30px, 5.5vw, 48px)",
    fontWeight: "700",
    color: "#222",
    marginBottom: "16px",
  },
  budgetSubtitle: {
    fontSize: "clamp(17px, 2.7vw, 22px)",
    color: "#555",
    marginBottom: "32px",
    lineHeight: 1.5,
  },
  budgetGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(3, 1fr)",
    gap: "clamp(16px, 2.4vw, 24px)",
    marginBottom: "28px",
  },
  budgetCard: {
    backgroundColor: "#ffffff",
    borderRadius: "20px",
    padding: "clamp(22px, 3vw, 28px) clamp(18px, 2.5vw, 20px)",
    fontSize: "clamp(18px, 2.8vw, 22px)",
    fontWeight: "600",
    color: "#222",
    lineHeight: 1.4,
    boxShadow: "0 6px 18px rgba(0, 0, 0, 0.08)",
  },
  budgetNote: {
    fontSize: "clamp(16px, 2.4vw, 20px)",
    color: "#555",
    maxWidth: "760px",
    margin: "0 auto",
    lineHeight: 1.6,
  },
};
