export const styles = {
  page: {
    minHeight: "100vh",
    backgroundColor: "#f7f5f1",
    color: "#222",
    fontFamily: "Arial, sans-serif",
  },
  container: {
    maxWidth: "1200px",
    margin: "0 auto",
    padding: "0 20px",
  },
  nav: {
    position: "sticky",
    top: 0,
    zIndex: 20,
    backgroundColor: "rgba(247,245,241,0.96)",
    borderBottom: "1px solid #ddd",
  },
  navInner: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "16px 0",
    flexWrap: "wrap",
    gap: "12px",
  },
  navButton: {
    background: "none",
    border: "none",
    cursor: "pointer",
    fontSize: "15px",
    color: "#555",
    textDecoration: "underline",
    textUnderlineOffset: "4px",
  },
  navButtonActive: {
    color: "#111",
    fontWeight: "bold",
  },
  heroTop: {
    textAlign: "center",
    paddingTop: "28px",
  },
  smallText: {
    fontSize: "14px",
    color: "#666",
  },
  title: {
    marginTop: "20px",
    fontSize: "48px",
    fontWeight: 300,
  },
  primaryButton: {
    marginTop: "24px",
    backgroundColor: "#c8102e",
    color: "white",
    border: "none",
    borderRadius: "999px",
    padding: "16px 28px",
    fontSize: "18px",
    cursor: "pointer",
  },
  section: {
    padding: "70px 0",
    textAlign: "center",
  },
  sectionTitle: {
    fontSize: "40px",
    fontWeight: 300,
    marginBottom: "16px",
  },
  sectionDesc: {
    maxWidth: "800px",
    margin: "0 auto",
    fontSize: "22px",
    color: "#555",
    lineHeight: 1.5,
  },
  threeCol: {
    display: "grid",
    gridTemplateColumns: "repeat(3, 1fr)",
    gap: "28px",
    marginTop: "44px",
  },
  featureCard: {
    backgroundColor: "#fff",
    borderRadius: "20px",
    padding: "24px",
    border: "1px solid #e5e5e5",
  },
  featuredDealsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(2, 1fr)",
    gap: "24px",
    marginTop: "36px",
  },
  featuredCard: {
    backgroundColor: "#fff",
    border: "1px solid #e5e5e5",
    borderRadius: "24px",
    padding: "24px",
    textAlign: "left",
  },
  featuredEmoji: {
    fontSize: "56px",
    marginBottom: "16px",
  },
  searchWrap: {
    maxWidth: "800px",
    margin: "28px auto 0",
    display: "flex",
    alignItems: "center",
    gap: "10px",
    backgroundColor: "#e9e9e9",
    borderRadius: "999px",
    padding: "14px 18px",
  },
  input: {
    flex: 1,
    border: "none",
    background: "transparent",
    outline: "none",
    fontSize: "16px",
  },
  filters: {
    marginTop: "28px",
    display: "flex",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: "12px",
  },
  filterButton: {
    borderRadius: "999px",
    padding: "10px 18px",
    border: "1px solid #ddd",
    backgroundColor: "#e9e9e9",
    cursor: "pointer",
    fontSize: "15px",
  },
  filterButtonActive: {
    backgroundColor: "#c8102e",
    color: "white",
    border: "1px solid #c8102e",
  },
  dealsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(3, 1fr)",
    gap: "28px",
    padding: "50px 0",
  },
  dealCard: {
    backgroundColor: "#fdeef1",
    padding: "28px 20px",
    textAlign: "center",
    minHeight: "340px",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    borderRadius: "18px",
  },
  iconCircle: {
    width: "140px",
    height: "140px",
    borderRadius: "50%",
    backgroundColor: "#fff",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    margin: "0 auto 24px",
    boxShadow: "0 4px 12px rgba(0, 0, 0, 0.08)",
  },
  dealBrand: {
    marginTop: "18px",
    fontSize: "30px",
    fontWeight: 600,
  },
  dealTitle: {
    marginTop: "14px",
    fontSize: "22px",
    lineHeight: 1.4,
  },
  logoImage: {
    width: "68px",
    height: "68px",
    objectFit: "contain",
  },
  meta: {
    marginTop: "auto",
    paddingTop: "18px",
    fontSize: "14px",
    color: "#666",
  },
  pager: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    gap: "12px",
    paddingBottom: "40px",
  },
  pagerButton: {
    border: "1px solid #ccc",
    backgroundColor: "white",
    borderRadius: "10px",
    padding: "8px 14px",
    cursor: "pointer",
  },
  footer: {
    backgroundColor: "#555",
    color: "white",
    marginTop: "40px",
    paddingTop: "18px",
  },
  footerGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "24px",
    padding: "20px 0 50px",
  },
  footerTitle: {
    fontSize: "30px",
    fontWeight: 600,
    marginBottom: "12px",
  },
  footerText: {
    fontSize: "20px",
    lineHeight: 1.6,
    color: "rgba(255,255,255,0.9)",
  },
  footerIcons: {
    display: "flex",
    gap: "16px",
    alignItems: "center",
    justifyContent: "flex-start",
    marginBottom: "24px",
    marginLeft: "0",
  },
  copyright: {
    fontSize: "14px",
    color: "rgba(255,255,255,0.8)",
    paddingBottom: "18px",
  },
  fullImageCard: {
    marginTop: "36px",
    borderRadius: "28px",
    overflow: "hidden",
    boxShadow: "0 2px 8px rgba(0,0,0,0.05)",
  },
  fullImage: {
    width: "100%",
    display: "block",
    borderRadius: "28px",
  },
  middleImageCard: {
    marginTop: "10px",
    marginBottom: "30px",
    borderRadius: "28px",
    overflow: "hidden",
  },
  middleImage: {
    width: "100%",
    display: "block",
    borderRadius: "28px",
  },
  footerHeroCard: {
    position: "relative",
    marginTop: "50px",
    borderRadius: "28px",
    overflow: "hidden",
  },
  footerHeroImage: {
    width: "100%",
    display: "block",
    borderRadius: "28px",
  },
  footerHeroOverlay: {
    position: "absolute",
    left: "50%",
    bottom: "8%",
    transform: "translateX(-50%)",
    textAlign: "center",
    width: "80%",
    zIndex: 2,
  },
  footerHeroTitle: {
    fontSize: "48px",
    fontWeight: 500,
    color: "white",
    marginBottom: "24px",
    textShadow: "0 2px 8px rgba(0,0,0,0.4)",
  },
  footerHeroButton: {
    backgroundColor: "#c8102e",
    color: "white",
    border: "none",
    borderRadius: "999px",
    padding: "16px 36px",
    fontSize: "24px",
    cursor: "pointer",
    boxShadow: "0 4px 12px rgba(0,0,0,0.25)",
  },
  footerHeroShade: {
    position: "absolute",
    inset: 0,
    backgroundColor: "rgba(0, 0, 0, 0.4)",
  },
  socialLink: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    textDecoration: "none",
  },
  socialIcon: {
    width: "24px",
    height: "24px",
    objectFit: "contain",
  },
  budgetSection: {
    maxWidth: "1200px",
    margin: "0 auto",
    padding: "60px 24px 50px",
    textAlign: "center",
  },
  budgetTitle: {
    fontSize: "48px",
    fontWeight: "700",
    color: "#222",
    marginBottom: "16px",
  },
  budgetSubtitle: {
    fontSize: "22px",
    color: "#555",
    marginBottom: "32px",
    lineHeight: 1.5,
  },
  budgetGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(3, 1fr)",
    gap: "24px",
    marginBottom: "28px",
  },
  budgetCard: {
    backgroundColor: "#ffffff",
    borderRadius: "20px",
    padding: "28px 20px",
    fontSize: "22px",
    fontWeight: "600",
    color: "#222",
    lineHeight: 1.4,
    boxShadow: "0 6px 18px rgba(0, 0, 0, 0.08)",
  },
  budgetNote: {
    fontSize: "20px",
    color: "#555",
    maxWidth: "760px",
    margin: "0 auto",
    lineHeight: 1.6,
  },
};
